spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?characterEncoding=utf-8
    username: root
    password: tangdu123
main:
  web-application-type: servlet
server:
  port: 8091
  servlet:
    context-path: ""